// This file was auto-generated by ML.NET Model Builder. 

using System;
using Tutorias_MLML.Model;

namespace Tutorias_MLML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string continuar = "";
            int sumPositivos = 0;
            int sumNegativos = 0;

            Console.WriteLine("\n");
            Console.WriteLine("----------PROGRAMA --------------------");
            Console.WriteLine("Introducir varias opiniones personales como queramos y evaluarlas con el aprendizaje autónomo\n");
            //Conteo de comentarios positivos y negativos
            do
            {

                Console.Write("Cual es su opinion en esta tutoria: ");
                string resp = Console.ReadLine();
                // Create single instance of sample data from first line of dataset for model input
                ModelInput sampleData = new ModelInput()
                {
                    Col0 = resp,

                };

                // Make a single prediction on the sample data and print results
                var predictionResult = ConsumeModel.Predict(sampleData);

                Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");
                //Console.WriteLine($"Col0: {sampleData.Col0}");
                // Console.WriteLine($"\n\nPredicted Col1 value {predictionResult.Prediction} \nPredicted Col1 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                string resul = predictionResult.Prediction.Equals("1") ? "Comentario Positivo" : "Comentario negativo";

                if (predictionResult.Prediction.Equals("1"))
                {
                    sumPositivos++;
                }
                else
                {
                    sumNegativos++;
                }
                Console.WriteLine(resp + " es un: " + resul);
                Console.WriteLine($"\n\nPredicted Col1 value {predictionResult.Prediction} \nPredicted Col1 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                Console.WriteLine("=============== End of process, hit any key to finish ===============");
                Console.WriteLine("desea realizar otra vez (S)/(N)");
                continuar = Console.ReadLine();
            } while (continuar == "S" || continuar == "s");
            Console.WriteLine("\nAnalizando--------------------------------------------------------------------");
            Console.WriteLine("El numero de comentarios positivos son: {0} y los negativos son {1} de: {2} comentarios", sumPositivos, sumNegativos, (sumPositivos + sumNegativos));
            Console.ReadKey();
        }
    }
}
